### ISSUE TITLE
replace orion patches with forked code

### ISSUE THREAD

**Issue by nickboldt** [eclipse/che-lib#93]
I've now tried to build che-lib in Brew and in che.openshift.io and in both places, the build fails to apply patches, but all the other projects build OK.

`Che Plugin :: Orion-14.0 :: Editor ................. FAILURE [  1.612 s]`

**Reproduction Steps:**

. Start che.openshift.io
. Import this project - https://github.com/eclipse/che-lib - from master branch
. In console:

`cd che-lib;
mvn clean install -DskipTests -fn`

Result:

compilation fails:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-patch-plugin:1.1.1:apply (bugfix-patches) on project che-orion-editor: Patch command
 failed with exit code 127 for fix_linked_mode.diff. Please see console and debug output for more information. -> [Help 1]`

**Che version:**    

6.9.0-SNAPSHOT

**OS and version:**    

`Linux workspace9nt5vd6igtvs72x2.dockerimage 3.10.0-862.3.2.el7.x86_64 #1 SMP Tue May 15 18:22:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Docker version:** 

(docker is not installed in my che.openshift.io workspace console)

**Che cli.log output:**  

No such file or directory

**Comment by skabashnyuk** [comment]
can we close this issue? @vparfonov @nickboldt ?
